[package]
name = "quick-translator"
version = "1.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
json = "0.12.4"
reqwest = { version = "0.11.13", features = ["blocking"] }
